name: KelpLib
version: '${version}'
main: ink.tuanzi.kelpLib.KelpLib
description: Shared utility & extension API library for the utoverse server family.
authors: [ evenwan ]
website: https://utoverse.net
api-version: '1.21'
load: STARTUP
folia-supported: true
libraries:
  - com.zaxxer:HikariCP:6.3.3
  - io.lettuce:lettuce-core:6.8.2.RELEASE
  - com.h2database:h2:2.5.252
  - org.xerial:sqlite-jdbc:3.53.4.0
  - com.mysql:mysql-connector-j:26.7.0
  - org.mariadb.jdbc:mariadb-java-client:3.5.10
